CREATE DATABASE M_Peoples;

USE M_Peoples;

CREATE TABLE TipoUsuario (
	IdTipo INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL UNIQUE
	);

CREATE TABLE Usuario (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (255) NOT NULL,
	IdTipo INT FOREIGN KEY REFERENCES TipoUsuario(IdTipo)
	);

CREATE TABLE Funcionarios (
	IdFuncionario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (255) NOT NULL,
	Sobrenome VARCHAR (255) NOT NULL,
	DataNascimento DATE NOT NULL
	);